2012-10-11T00:39:01+02:00 WARNING{"errstr":"Undefined variable: obj","errfile":"\/var\/www\/apps\/billing\/controller.class.php","errline":112,"errno":8}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"Undefined variable: obj","errfile":"\/var\/www\/apps\/billing\/controller.class.php","errline":112,"errno":8}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"Missing argument 2 for helper\\lodo::__construct(), called in \/var\/www\/helpers\/lodo\/controller.class.php on line 240 and defined","errfile":"\/var\/www\/helpers\/lodo\/controller.class.php","errline":95,"errno":2}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"Undefined variable: app","errfile":"\/var\/www\/helpers\/lodo\/controller.class.php","errline":100,"errno":8}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"Undefined variable: app","errfile":"\/var\/www\/helpers\/lodo\/controller.class.php","errline":103,"errno":8}
2012-10-11T00:40:44+02:00 ERROR{"message":"groups has to be an array","file":"implement","line":"implement"}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"Undefined index: favicon.ico","errfile":"\/var\/www\/start\/finance\/api.class.php","errline":367,"errno":8}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"Trying to get property of non-object","errfile":"\/var\/www\/start\/finance\/api.class.php","errline":367,"errno":8}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"Undefined index: favicon.ico","errfile":"\/var\/www\/start\/finance\/api.class.php","errline":368,"errno":8}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"Trying to get property of non-object","errfile":"\/var\/www\/start\/finance\/api.class.php","errline":368,"errno":8}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"unable to load class: app\\favicon.ico in \/var\/www\/apps\/favicon.ico\/controller.class.php or \/var\/www\/apps\/favicon.ico.class.php","errfile":"\/var\/www\/webroot\/index.php","errline":107,"errno":512}
2012-10-11T00:40:44+02:00 WARNING{"errstr":"Page index does not exist in app \\app\\favicon.ico.","errfile":"\/var\/www\/core\/reqHandler.class.php","errline":96,"errno":1024}
2012-10-11T00:41:56+02:00 ERROR {"message":"groups has to be an array","file":"implement","line":"implement"}
2012-11-04T16:11:44+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:12:22+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:14:39+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:38:48+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:39:10+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:39:37+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:39:45+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:39:50+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:40:19+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:40:34+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T16:40:36+01:00 ERROR {"message":"Not yet implemented","file":"implement","line":"implement"}
2012-11-04T20:28:57+01:00 ERROR {"message":"Couldn't do conversion","file":"implement","line":"implement"}
2012-11-06T18:04:00+01:00 ERROR {"message":"Property \"cvr\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:32:10+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:32:15+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:32:45+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:33:27+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:34:41+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:35:00+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:35:01+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:35:29+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:36:35+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:37:08+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:37:43+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:37:59+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:38:23+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:38:28+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-06T19:39:16+01:00 ERROR {"message":"Property \"schemeID\" doesn't exist in model\\ext\\ubl2\\PartyLegalEntity","file":"implement","line":"implement"}
2012-11-13T22:04:11+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","file":"implement","line":"implement"}
2012-11-13T22:07:57+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","file":"implement","line":"implement"}
2012-11-13T22:14:33+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","file":"implement","line":"implement"}
2012-11-13T22:21:03+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","file":"implement","line":"implement"}
2012-11-13T22:24:58+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","stack":"#0 [internal function]: jsonRPCClient->__call('add', Array)\n#1 [internal function]: jsonRPCClient->add(Array)\n#2 \/var\/www\/helpers\/rpc\/controller.class.php(26): call_user_func_array(Array, Array)\n#3 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc->__call('add', Array)\n#4 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc\\Finance->add(Array)\n#5 \/var\/www\/start\/finance\/controller.class.php(171): start\\finance\\api::createUser(Object(model\\finance\\platform\\UserCreate))\n#6 [internal function]: start\\finance\\main->createUser()\n#7 \/var\/www\/core\/reqHandler.class.php(126): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#9 {main}"}
2012-11-13T22:36:39+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","stack":"#0 [internal function]: jsonRPCClient->__call('add', Array)\n#1 [internal function]: jsonRPCClient->add(Array)\n#2 \/var\/www\/helpers\/rpc\/controller.class.php(26): call_user_func_array(Array, Array)\n#3 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc->__call('add', Array)\n#4 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc\\Finance->add(Array)\n#5 \/var\/www\/start\/finance\/controller.class.php(171): start\\finance\\api::createUser(Object(model\\finance\\platform\\UserCreate))\n#6 [internal function]: start\\finance\\main->createUser()\n#7 \/var\/www\/core\/reqHandler.class.php(126): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#9 {main}"}
2012-11-13T23:05:49+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","stack":"#0 [internal function]: jsonRPCClient->__call('add', Array)\n#1 [internal function]: jsonRPCClient->add(Array)\n#2 \/var\/www\/helpers\/rpc\/controller.class.php(26): call_user_func_array(Array, Array)\n#3 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc->__call('add', Array)\n#4 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc\\Finance->add(Array)\n#5 \/var\/www\/start\/finance\/controller.class.php(171): start\\finance\\api::createUser(Object(model\\finance\\platform\\UserCreate))\n#6 [internal function]: start\\finance\\main->createUser()\n#7 \/var\/www\/core\/reqHandler.class.php(126): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#9 {main}"}
2012-11-13T23:39:04+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","stack":"#0 [internal function]: jsonRPCClient->__call('add', Array)\n#1 [internal function]: jsonRPCClient->add(Array)\n#2 \/var\/www\/helpers\/rpc\/controller.class.php(26): call_user_func_array(Array, Array)\n#3 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc->__call('add', Array)\n#4 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc\\Finance->add(Array)\n#5 \/var\/www\/start\/finance\/controller.class.php(171): start\\finance\\api::createUser(Object(model\\finance\\platform\\UserCreate))\n#6 [internal function]: start\\finance\\main->createUser()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#9 {main}"}
2012-11-13T23:46:57+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","stack":"#0 [internal function]: jsonRPCClient->__call('add', Array)\n#1 [internal function]: jsonRPCClient->add(Array)\n#2 \/var\/www\/helpers\/rpc\/controller.class.php(26): call_user_func_array(Array, Array)\n#3 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc->__call('add', Array)\n#4 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc\\Finance->add(Array)\n#5 \/var\/www\/start\/finance\/controller.class.php(171): start\\finance\\api::createUser(Object(model\\finance\\platform\\UserCreate))\n#6 [internal function]: start\\finance\\main->createUser()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#9 {main}"}
2012-11-13T23:48:46+01:00 ERROR {"message":"Incorrect response id (request id: 1, response id: )","stack":"#0 [internal function]: jsonRPCClient->__call('add', Array)\n#1 [internal function]: jsonRPCClient->add(Array)\n#2 \/var\/www\/helpers\/rpc\/controller.class.php(26): call_user_func_array(Array, Array)\n#3 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc->__call('add', Array)\n#4 \/var\/www\/start\/finance\/api.class.php(83): helper\\rpc\\Finance->add(Array)\n#5 \/var\/www\/start\/finance\/controller.class.php(171): start\\finance\\api::createUser(Object(model\\finance\\platform\\UserCreate))\n#6 [internal function]: start\\finance\\main->createUser()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#9 {main}"}
2012-11-14T11:34:06+01:00 ERROR {"message":"groups has to be an array","stack":"#0 \/var\/www\/helpers\/lodo\/controller.class.php(106): helper\\lodo->setGroups(false)\n#1 \/var\/www\/helpers\/lodo\/controller.class.php(240): helper\\lodo->__construct(Array)\n#2 \/var\/www\/apps\/billing\/api.class.php(114): helper\\lodo->insert(NULL)\n#3 \/var\/www\/apps\/billing\/controller.class.php(112): api\\billing::create(NULL)\n#4 [internal function]: app\\billing->create()\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#7 {main}"}
2012-11-14T11:34:13+01:00 ERROR {"message":"groups has to be an array","stack":"#0 \/var\/www\/helpers\/lodo\/controller.class.php(106): helper\\lodo->setGroups(false)\n#1 \/var\/www\/helpers\/lodo\/controller.class.php(240): helper\\lodo->__construct(Array)\n#2 \/var\/www\/apps\/billing\/api.class.php(114): helper\\lodo->insert(NULL)\n#3 \/var\/www\/apps\/billing\/controller.class.php(112): api\\billing::create(NULL)\n#4 [internal function]: app\\billing->create()\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#7 {main}"}
2012-11-14T11:36:26+01:00 ERROR {"message":"groups has to be an array","stack":"#0 \/var\/www\/helpers\/lodo\/controller.class.php(106): helper\\lodo->setGroups(false)\n#1 \/var\/www\/helpers\/lodo\/controller.class.php(240): helper\\lodo->__construct(Array)\n#2 \/var\/www\/apps\/billing\/api.class.php(114): helper\\lodo->insert(NULL)\n#3 \/var\/www\/apps\/billing\/controller.class.php(112): api\\billing::create(NULL)\n#4 [internal function]: app\\billing->create()\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#7 {main}"}
2012-11-14T11:36:31+01:00 ERROR {"message":"groups has to be an array","stack":"#0 \/var\/www\/helpers\/lodo\/controller.class.php(106): helper\\lodo->setGroups(false)\n#1 \/var\/www\/helpers\/lodo\/controller.class.php(240): helper\\lodo->__construct(Array)\n#2 \/var\/www\/apps\/billing\/api.class.php(114): helper\\lodo->insert(NULL)\n#3 \/var\/www\/apps\/billing\/controller.class.php(112): api\\billing::create(NULL)\n#4 [internal function]: app\\billing->create()\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#7 {main}"}
2012-11-14T11:37:10+01:00 ERROR {"message":"Property \"product\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('product', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(111): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-14T11:39:03+01:00 ERROR {"message":"Property \"product\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('product', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(111): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-14T11:40:05+01:00 ERROR {"message":"Property \"products\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('products', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(111): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-14T11:40:07+01:00 ERROR {"message":"Property \"products\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('products', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(111): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-14T19:24:35+01:00 ERROR {"message":"Property \"0\" doesn't exist in model\\ext\\ubl2\\Invoice","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set(0, Array)\n#1 \/var\/www\/model\/AbstractModel.class.php(180): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Invoice', Array)\n#3 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#4 \/var\/www\/apps\/billing\/controller.class.php(111): helper\\parser\\Post->getObj()\n#5 [internal function]: app\\billing->create()\n#6 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#7 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#8 {main}"}
2012-11-14T19:25:44+01:00 ERROR {"message":"Property \"vatAmount\" doesn't exist in model\\ext\\ubl2\\InvoiceLine","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('vatAmount', '')\n#1 \/var\/www\/model\/Iterator.class.php(33): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/model\/AbstractModel.class.php(117): model\\Iterator->set(0, Array)\n#3 \/var\/www\/model\/Iterator.class.php(22): model\\AbstractModel->__construct(Array)\n#4 \/var\/www\/model\/AbstractModel.class.php(172): model\\Iterator->__construct(Array, '\\model\\ext\\ubl2...')\n#5 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('InvoiceLine', Array)\n#6 \/var\/www\/model\/AbstractModel.class.php(180): model\\AbstractModel->__construct(Array)\n#7 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Invoice', Array)\n#8 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#9 \/var\/www\/apps\/billing\/controller.class.php(111): helper\\parser\\Post->getObj()\n#10 [internal function]: app\\billing->create()\n#11 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#12 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#13 {main}"}
2012-11-15T00:17:52+01:00 ERROR {"message":"Property \"vat\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('vat', 'on')\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(111): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-15T00:18:21+01:00 ERROR {"message":"Property \"products\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('products', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(111): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-15T00:28:14+01:00 ERROR {"message":"Property \"vatAmount\" doesn't exist in model\\finance\\bill\\Product","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('vatAmount', '0,00')\n#1 \/var\/www\/model\/Iterator.class.php(33): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/model\/AbstractModel.class.php(117): model\\Iterator->set(0, Array)\n#3 \/var\/www\/model\/Iterator.class.php(22): model\\AbstractModel->__construct(Array)\n#4 \/var\/www\/model\/AbstractModel.class.php(172): model\\Iterator->__construct(Array, '\\model\\finance\\...')\n#5 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('product', Array)\n#6 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#7 \/var\/www\/apps\/billing\/controller.class.php(112): helper\\parser\\Post->getObj()\n#8 [internal function]: app\\billing->create()\n#9 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#10 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#11 {main}"}
2012-11-15T00:30:45+01:00 ERROR {"message":"Property \"productInclVat\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('productInclVat', false)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(112): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-15T00:33:27+01:00 ERROR {"message":"groups has to be an array","stack":"#0 \/var\/www\/helpers\/lodo\/controller.class.php(106): helper\\lodo->setGroups(false)\n#1 \/var\/www\/helpers\/lodo\/controller.class.php(240): helper\\lodo->__construct(Array)\n#2 \/var\/www\/apps\/billing\/api.class.php(114): helper\\lodo->insert(NULL)\n#3 \/var\/www\/apps\/billing\/controller.class.php(106): api\\billing::create(NULL)\n#4 [internal function]: app\\billing->create()\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#7 {main}"}
2012-11-16T00:42:11+01:00 ERROR {"message":"Property \"Price\" doesn't exist in model\\finance\\bill\\Product","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Price', Array)\n#1 \/var\/www\/model\/Iterator.class.php(33): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/model\/AbstractModel.class.php(117): model\\Iterator->set(0, Array)\n#3 \/var\/www\/model\/Iterator.class.php(22): model\\AbstractModel->__construct(Array)\n#4 \/var\/www\/model\/AbstractModel.class.php(172): model\\Iterator->__construct(Array, '\\model\\finance\\...')\n#5 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('product', Array)\n#6 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#7 \/var\/www\/apps\/billing\/controller.class.php(116): helper\\parser\\Post->getObj()\n#8 [internal function]: app\\billing->create()\n#9 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#10 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#11 {main}"}
2012-11-29T00:24:51+01:00 ERROR {"message":"Property \"Invoice\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Invoice', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(122): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-29T01:00:52+01:00 ERROR {"message":"Property \"Invoice\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Invoice', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(122): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-29T11:35:18+01:00 ERROR {"message":"Property \"Invoice\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Invoice', Array)\n#1 \/var\/www\/helpers\/lodo\/controller.class.php(372): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/api.class.php(177): helper\\lodo->getObjects('\\model\\finance\\...')\n#3 \/var\/www\/apps\/billing\/api.class.php(40): api\\billing::get(NULL, NULL, 3)\n#4 [internal function]: api\\billing::on_getWidget()\n#5 \/var\/www\/core\/app.class.php(84): call_user_func(Array)\n#6 \/var\/www\/start\/finance\/controller.class.php(123): core\\app->callAll('getWidget')\n#7 [internal function]: start\\finance\\main->apps()\n#8 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#9 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#10 {main}"}
2012-11-29T11:41:40+01:00 ERROR {"message":"Property \"Invoice\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Invoice', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(122): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-29T11:43:39+01:00 ERROR {"message":"Property \"Invoice\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Invoice', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(122): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-29T11:45:12+01:00 ERROR {"message":"Property \"Invoice\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Invoice', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(120): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-29T11:51:07+01:00 ERROR {"message":"Property \"Invoice\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('Invoice', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(120): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#6 {main}"}
2012-11-29T11:54:59+01:00 ERROR {"message":"Property \"Invoice\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(217): model\\AbstractModel->set('Invoice', Array)\n#1 \/var\/www\/apps\/billing\/api.class.php(297): model\\AbstractModel->merge(Array)\n#2 \/var\/www\/apps\/billing\/api.class.php(128): api\\billing::billObject(Object(model\\finance\\Bill))\n#3 \/var\/www\/apps\/billing\/controller.class.php(125): api\\billing::create(Object(model\\finance\\Bill))\n#4 [internal function]: app\\billing->create()\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#7 {main}"}
2012-11-29T11:56:53+01:00 ERROR {"message":"Property \"Invoice\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(217): model\\AbstractModel->set('Invoice', Array)\n#1 \/var\/www\/apps\/billing\/api.class.php(297): model\\AbstractModel->merge(Array)\n#2 \/var\/www\/apps\/billing\/api.class.php(128): api\\billing::billObject(Object(model\\finance\\Bill))\n#3 \/var\/www\/apps\/billing\/controller.class.php(125): api\\billing::create(Object(model\\finance\\Bill))\n#4 [internal function]: app\\billing->create()\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#7 {main}"}
2012-11-30T16:35:32+01:00 ERROR {"message":"Product \"506951df1as5f015d44000001\" not found","stack":"#0 \/var\/www\/apps\/products\/controller.class.php(74): api\\products::getOne('506951df1as5f01...')\n#1 [internal function]: app\\products->view('506951df1as5f01...')\n#2 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#3 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#4 {main}"}
2012-11-30T16:43:07+01:00 ERROR {"message":"Quantity must be more than 0, value: -4","stack":"#0 \/var\/www\/apps\/billing\/api.class.php(142): api\\billing::billObject(Object(model\\finance\\Bill))\n#1 \/var\/www\/apps\/billing\/rpc.class.php(29): api\\billing::create(Object(model\\finance\\Bill))\n#2 [internal function]: rpc\\billing->create(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#5 {main}"}
2012-11-30T16:43:08+01:00 ERROR {"message":"Contact blahBlahBlah doesn' exist","stack":"#0 \/var\/www\/apps\/billing\/api.class.php(142): api\\billing::billObject(Object(model\\finance\\Bill))\n#1 \/var\/www\/apps\/billing\/rpc.class.php(29): api\\billing::create(Object(model\\finance\\Bill))\n#2 [internal function]: rpc\\billing->create(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#5 {main}"}
2012-11-30T16:43:09+01:00 ERROR {"message":"Requested bill doesn't exist","stack":"#0 \/var\/www\/apps\/billing\/rpc.class.php(46): api\\billing::getOne('IdThatDontExist')\n#1 [internal function]: rpc\\billing->get('IdThatDontExist')\n#2 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#3 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#4 {main}"}
2012-11-30T16:44:54+01:00 ERROR {"message":"Contact blahBlahBlah doesn' exist","stack":"#0 \/var\/www\/apps\/billing\/api.class.php(142): api\\billing::billObject(Object(model\\finance\\Bill))\n#1 \/var\/www\/apps\/billing\/rpc.class.php(29): api\\billing::create(Object(model\\finance\\Bill))\n#2 [internal function]: rpc\\billing->create(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#5 {main}"}
2012-11-30T16:44:55+01:00 ERROR {"message":"Requested bill doesn't exist","stack":"#0 \/var\/www\/apps\/billing\/rpc.class.php(46): api\\billing::getOne('IdThatDontExist')\n#1 [internal function]: rpc\\billing->get('IdThatDontExist')\n#2 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#3 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#4 {main}"}
2012-11-30T16:45:24+01:00 ERROR {"message":"Requested bill doesn't exist","stack":"#0 \/var\/www\/apps\/billing\/rpc.class.php(46): api\\billing::getOne('IdThatDontExist')\n#1 [internal function]: rpc\\billing->get('IdThatDontExist')\n#2 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#3 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#4 {main}"}
2012-12-01T18:57:10+01:00 ERROR {"message":"type is not valid","stack":"#0 \/var\/www\/apps\/accounting\/api.class.php(356): helper\\accounting->createAccount(Array)\n#1 \/var\/www\/apps\/accounting\/rpc.class.php(26): api\\accounting::createAccount(Array)\n#2 [internal function]: rpc\\accounting->create(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#5 {main}"}
2012-12-01T21:29:45+01:00 ERROR {"message":"type is not valid","stack":"#0 \/var\/www\/apps\/accounting\/api.class.php(356): helper\\accounting->createAccount(Array)\n#1 \/var\/www\/apps\/accounting\/rpc.class.php(26): api\\accounting::createAccount(Array)\n#2 [internal function]: rpc\\accounting->create(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#5 {main}"}
2012-12-01T21:31:34+01:00 ERROR {"message":"type is not valid","stack":"#0 \/var\/www\/apps\/accounting\/api.class.php(356): helper\\accounting->createAccount(NULL)\n#1 \/var\/www\/apps\/accounting\/rpc.class.php(27): api\\accounting::createAccount(NULL)\n#2 [internal function]: rpc\\accounting->create(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#5 {main}"}
2012-12-01T21:45:29+01:00 ERROR {"message":"","stack":"#0 \/var\/www\/apps\/accounting\/api.class.php(356): helper\\accounting->createAccount(Object(model\\finance\\accounting\\Account))\n#1 \/var\/www\/apps\/accounting\/rpc.class.php(27): api\\accounting::createAccount(Object(model\\finance\\accounting\\Account))\n#2 [internal function]: rpc\\accounting->create(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(193): core\\reqHandler::init()\n#5 {main}"}
2012-12-02T13:34:26+01:00 ERROR {"message":"Property \"vatCode\" doesn't exist in model\\finance\\bill\\Line","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('vatCode', 'I25')\n#1 \/var\/www\/model\/Iterator.class.php(33): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/model\/AbstractModel.class.php(117): model\\Iterator->set(0, Array)\n#3 \/var\/www\/model\/Iterator.class.php(22): model\\AbstractModel->__construct(Array)\n#4 \/var\/www\/model\/AbstractModel.class.php(172): model\\Iterator->__construct(Array, '\\model\\finance\\...')\n#5 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('lines', Array)\n#6 \/var\/www\/helpers\/lodo\/controller.class.php(397): model\\AbstractModel->__construct(Array)\n#7 \/var\/www\/apps\/billing\/api.class.php(195): helper\\lodo->getObjects('\\model\\finance\\...')\n#8 \/var\/www\/apps\/billing\/api.class.php(47): api\\billing::get(NULL, NULL, 3)\n#9 [internal function]: api\\billing::on_getWidget()\n#10 \/var\/www\/core\/app.class.php(84): call_user_func(Array)\n#11 \/var\/www\/start\/finance\/controller.class.php(123): core\\app->callAll('getWidget')\n#12 [internal function]: start\\finance\\main->apps()\n#13 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#14 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#15 {main}"}
2012-12-02T15:13:24+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=lo...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/logHandler.class.php(155): core\\db->__construct(Array)\n#2 \/var\/www\/core\/logHandler.class.php(141): core\\logHandler::writeDB(Array, 'stats_sessions')\n#3 \/var\/www\/core\/session.class.php(35): core\\logHandler::statistic('stats_sessions')\n#4 \/var\/www\/core\/auth.class.php(51): core\\session::getInstance()\n#5 \/var\/www\/core\/auth.class.php(19): core\\auth->__construct()\n#6 \/var\/www\/core\/reqHandler.class.php(27): core\\auth::getInstance()\n#7 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#8 {main}"}
2012-12-02T15:13:28+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=lo...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/logHandler.class.php(155): core\\db->__construct(Array)\n#2 \/var\/www\/core\/logHandler.class.php(141): core\\logHandler::writeDB(Array, 'stats_sessions')\n#3 \/var\/www\/core\/session.class.php(35): core\\logHandler::statistic('stats_sessions')\n#4 \/var\/www\/core\/auth.class.php(51): core\\session::getInstance()\n#5 \/var\/www\/core\/auth.class.php(19): core\\auth->__construct()\n#6 \/var\/www\/core\/reqHandler.class.php(27): core\\auth::getInstance()\n#7 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#8 {main}"}
2012-12-02T15:13:28+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=lo...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/logHandler.class.php(155): core\\db->__construct(Array)\n#2 \/var\/www\/core\/logHandler.class.php(141): core\\logHandler::writeDB(Array, 'stats_sessions')\n#3 \/var\/www\/core\/session.class.php(35): core\\logHandler::statistic('stats_sessions')\n#4 \/var\/www\/core\/auth.class.php(51): core\\session::getInstance()\n#5 \/var\/www\/core\/auth.class.php(19): core\\auth->__construct()\n#6 \/var\/www\/core\/reqHandler.class.php(27): core\\auth::getInstance()\n#7 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#8 {main}"}
2012-12-02T15:13:28+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=lo...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/logHandler.class.php(155): core\\db->__construct(Array)\n#2 \/var\/www\/core\/logHandler.class.php(141): core\\logHandler::writeDB(Array, 'stats_sessions')\n#3 \/var\/www\/core\/session.class.php(35): core\\logHandler::statistic('stats_sessions')\n#4 \/var\/www\/core\/auth.class.php(51): core\\session::getInstance()\n#5 \/var\/www\/core\/auth.class.php(19): core\\auth->__construct()\n#6 \/var\/www\/core\/reqHandler.class.php(27): core\\auth::getInstance()\n#7 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#8 {main}"}
2012-12-02T15:13:28+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=lo...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/logHandler.class.php(155): core\\db->__construct(Array)\n#2 \/var\/www\/core\/logHandler.class.php(141): core\\logHandler::writeDB(Array, 'stats_sessions')\n#3 \/var\/www\/core\/session.class.php(35): core\\logHandler::statistic('stats_sessions')\n#4 \/var\/www\/core\/auth.class.php(51): core\\session::getInstance()\n#5 \/var\/www\/core\/auth.class.php(19): core\\auth->__construct()\n#6 \/var\/www\/core\/reqHandler.class.php(27): core\\auth::getInstance()\n#7 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#8 {main}"}
2012-12-02T15:13:28+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=lo...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/logHandler.class.php(155): core\\db->__construct(Array)\n#2 \/var\/www\/core\/logHandler.class.php(141): core\\logHandler::writeDB(Array, 'stats_sessions')\n#3 \/var\/www\/core\/session.class.php(35): core\\logHandler::statistic('stats_sessions')\n#4 \/var\/www\/core\/auth.class.php(51): core\\session::getInstance()\n#5 \/var\/www\/core\/auth.class.php(19): core\\auth->__construct()\n#6 \/var\/www\/core\/reqHandler.class.php(27): core\\auth::getInstance()\n#7 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#8 {main}"}
2012-12-02T15:13:44+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(141): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/start\/finance\/controller.class.php(36): start\\finance\\api::login('madspbuch@gmail...', '123456')\n#6 [internal function]: start\\finance\\main->index()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#9 {main}"}
2012-12-03T00:46:49+01:00 ERROR {"message":"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:06+01:00 ERROR {"message":"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:06+01:00 ERROR {"message":"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:06+01:00 ERROR {"message":"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:06+01:00 ERROR {"message":"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:06+01:00 ERROR {"message":"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:00+01:00 ERROR {"message":"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:06+01:00 ERROR {"message":"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:46:46+01:00 ERROR {"message":"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:42+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:49+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:56+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:56+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:56+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:56+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:56+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:47:59+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:50:50+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:50:57+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:50:57+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:50:57+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:50:57+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:15+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:15+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:18+01:00 ERROR {"message":"couldn't send command","stack":"#0 \/var\/www\/start\/finance\/api.class.php(244): MongoCursor->count()\n#1 \/var\/www\/start\/finance\/api.class.php(184): start\\finance\\api::getAPIKeys('4e50d016a6f29dc...', false)\n#2 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#3 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#4 {main}"}
2012-12-03T00:51:15+01:00 ERROR {"message":"couldn't send command","stack":"#0 \/var\/www\/start\/finance\/api.class.php(244): MongoCursor->count()\n#1 \/var\/www\/start\/finance\/api.class.php(184): start\\finance\\api::getAPIKeys('4e50d016a6f29dc...', false)\n#2 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#3 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#4 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:37+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:51:48+01:00 ERROR {"message":"couldn't send command","stack":"#0 \/var\/www\/start\/finance\/api.class.php(244): MongoCursor->count()\n#1 \/var\/www\/start\/finance\/api.class.php(184): start\\finance\\api::getAPIKeys('4e50d016a6f29dc...', false)\n#2 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#3 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#4 {main}"}
2012-12-03T00:51:48+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:52:24+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:53:06+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:53:14+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:50:50+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(196): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/core\/reqHandler.class.php(56): start\\finance\\api::authenticate()\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T00:53:53+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(574): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(202): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(140): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.cl2012-12-03T00:56:39+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=fi...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/db.class.php(18): core\\db->__construct('finance')\n#2 \/var\/www\/helpers\/core\/controller.class.php(181): core\\db::getInstance('finance', 'mysql')\n#3 \/var\/www\/helpers\/accounting\/controller.class.php(63): helper\\core->getDB()\n#4 \/var\/www\/apps\/accounting\/api.class.php(385): helper\\accounting->__construct('506951c41a5f010...')\n#5 \/var\/www\/apps\/accounting\/api.class.php(56): api\\accounting::getAccounts(true)\n#6 [internal function]: api\\accounting::on_getWidget()\n#7 \/var\/www\/core\/app.class.php(84): call_user_func(Array)\n#8 \/var\/www\/start\/finance\/controller.class.php(123): core\\app->callAll('getWidget')\n#9 [internal function]: start\\finance\\main->apps()\n#10 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#11 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#12 {main}"}
2012-12-03T00:57:34+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=fi...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/db.class.php(18): core\\db->__construct('finance')\n#2 \/var\/www\/helpers\/core\/controller.class.php(181): core\\db::getInstance('finance', 'mysql')\n#3 \/var\/www\/helpers\/accounting\/controller.class.php(63): helper\\core->getDB()\n#4 \/var\/www\/apps\/accounting\/api.class.php(385): helper\\accounting->__construct('506951c41a5f010...')\n#5 \/var\/www\/apps\/accounting\/api.class.php(56): api\\accounting::getAccounts(true)\n#6 [internal function]: api\\accounting::on_getWidget()\n#7 \/var\/www\/core\/app.class.php(84): call_user_func(Array)\n#8 \/var\/www\/start\/finance\/controller.class.php(123): core\\app->callAll('getWidget')\n#9 [internal function]: start\\finance\\main->apps()\n#10 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#11 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#12 {main}"}
2012-12-03T00:57:36+01:00 ERROR {"message":"SQLSTATE[HY000] [1129] Host '192.168.1.22' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=fi...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/db.class.php(18): core\\db->__construct('finance')\n#2 \/var\/www\/helpers\/core\/controller.class.php(181): core\\db::getInstance('finance', 'mysql')\n#3 \/var\/www\/helpers\/accounting\/controller.class.php(63): helper\\core->getDB()\n#4 \/var\/www\/apps\/accounting\/api.class.php(385): helper\\accounting->__construct('506951c41a5f010...')\n#5 \/var\/www\/apps\/accounting\/api.class.php(56): api\\accounting::getAccounts(true)\n#6 [internal function]: api\\accounting::on_getWidget()\n#7 \/var\/www\/core\/app.class.php(84): call_user_func(Array)\n#8 \/var\/www\/start\/finance\/controller.class.php(123): core\\app->callAll('getWidget')\n#9 [internal function]: start\\finance\\main->apps()\n#10 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#11 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#12 {main}"}
2012-12-03T21:28:49+01:00 ERROR {"message":"Account \"\" does not exist.","stack":"#0 \/var\/www\/helpers\/accounting\/controller.class.php(140): helper\\accounting->addTransaction(Object(model\\finance\\accounting\\Transaction))\n#1 \/var\/www\/apps\/accounting\/api.class.php(364): helper\\accounting->addDaybookTransaction(Object(model\\finance\\accounting\\DaybookTransaction))\n#2 \/var\/www\/apps\/billing\/api.class.php(295): api\\accounting::importTransactions(Object(model\\finance\\accounting\\DaybookTransaction))\n#3 \/var\/www\/apps\/billing\/rpc.class.php(89): api\\billing::bookkeep('50bd0b801a5f019...', 12320, 13110)\n#4 [internal function]: rpc\\billing->post('50bd0b801a5f019...', 12320, 13110)\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-03T21:38:19+01:00 ERROR {"message":"Property \"productIDs\" doesn't exist in model\\finance\\Invoice","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(141): model\\AbstractModel->set('productIDs', Object(model\\Iterator))\n#1 \/var\/www\/model\/AbstractModel.class.php(123): model\\AbstractModel->__set('productIDs', Object(model\\Iterator))\n#2 \/var\/www\/helpers\/lodo\/controller.class.php(397): model\\AbstractModel->__construct(Array)\n#3 \/var\/www\/apps\/invoice\/api.class.php(120): helper\\lodo->getObjects('\\model\\finance\\...')\n#4 \/var\/www\/apps\/invoice\/api.class.php(70): api\\invoice::get(NULL, 3, Array)\n#5 [internal function]: api\\invoice::on_getWidget()\n#6 \/var\/www\/core\/app.class.php(84): call_user_func(Array)\n#7 \/var\/www\/start\/finance\/controller.class.php(123): core\\app->callAll('getWidget')\n#8 [internal function]: start\\finance\\main->apps()\n#9 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#10 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#11 {main}"}
2012-12-03T21:59:16+01:00 ERROR {"message":"assets and libilities should equal up to 0","stack":"#0 \/var\/www\/apps\/accounting\/api.class.php(365): helper\\accounting->commit()\n#1 \/var\/www\/apps\/billing\/api.class.php(303): api\\accounting::importTransactions(Object(model\\finance\\accounting\\DaybookTransaction))\n#2 \/var\/www\/apps\/billing\/rpc.class.php(89): api\\billing::bookkeep('50bd12a41a5f018...', 12320, 13110)\n#3 [internal function]: rpc\\billing->post('50bd12a41a5f018...', 12320, 13110)\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#6 {main}"}
2012-12-08T00:31:57+01:00 ERROR {"message":"Can't take a write lock while out of disk space","stack":"#0 \/var\/www\/helpers\/lodo\/controller.class.php(254): MongoCollection->insert(Array, Array)\n#1 \/var\/www\/apps\/billing\/api.class.php(150): helper\\lodo->insert(Object(model\\finance\\Bill))\n#2 \/var\/www\/apps\/billing\/rpc.class.php(31): api\\billing::create(Object(model\\finance\\Bill))\n#3 [internal function]: rpc\\billing->create(Array)\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#6 {main}"}
2012-12-08T00:32:01+01:00 ERROR {"message":"Can't take a write lock while out of disk space","stack":"#0 \/var\/www\/helpers\/lodo\/controller.class.php(254): MongoCollection->insert(Array, Array)\n#1 \/var\/www\/apps\/billing\/api.class.php(150): helper\\lodo->insert(Object(model\\finance\\Bill))\n#2 \/var\/www\/apps\/billing\/rpc.class.php(31): api\\billing::create(Object(model\\finance\\Bill))\n#3 [internal function]: rpc\\billing->create(Array)\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#6 {main}"}
2012-12-08T00:32:16+01:00 ERROR {"message":"Can't take a write lock while out of disk space","stack":"#0 \/var\/www\/helpers\/lodo\/controller.class.php(254): MongoCollection->insert(Array, Array)\n#1 \/var\/www\/apps\/billing\/api.class.php(150): helper\\lodo->insert(Object(model\\finance\\Bill))\n#2 \/var\/www\/apps\/billing\/rpc.class.php(31): api\\billing::create(Object(model\\finance\\Bill))\n#3 [internal function]: rpc\\billing->create(Array)\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#6 {main}"}
2012-12-08T15:17:55+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(577): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(205): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(143): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(141): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/start\/finance\/controller.class.php(36): start\\finance\\api::login('madspbuch@gmail...', '123456')\n#6 [internal function]: start\\finance\\main->index()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#9 {main}"}
2012-12-08T15:18:29+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(577): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(205): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(143): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(141): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/start\/finance\/controller.class.php(36): start\\finance\\api::login('madspbuch@gmail...', '123456')\n#6 [internal function]: start\\finance\\main->index()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#9 {main}"}
2012-12-08T15:18:44+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.18' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(577): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(205): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(143): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(141): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/start\/finance\/controller.class.php(36): start\\finance\\api::login('madspbuch@gmail...', '123456')\n#6 [internal function]: start\\finance\\main->index()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#9 {main}"}
2012-12-09T02:07:26+01:00 ERROR {"message":"Product \"\" not found","stack":"#0 \/var\/www\/apps\/billing\/api.class.php(342): api\\products::getOne('')\n#1 \/var\/www\/apps\/billing\/api.class.php(142): api\\billing::billObject(Object(model\\finance\\Bill))\n#2 \/var\/www\/apps\/billing\/controller.class.php(141): api\\billing::create(Object(model\\finance\\Bill))\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#6 {main}"}
2012-12-09T20:08:07+01:00 ERROR {"message":"No id set on the object","stack":"#0 \/var\/www\/apps\/billing\/api.class.php(226): helper\\lodo->update(Object(model\\finance\\Bill))\n#1 \/var\/www\/apps\/billing\/rpc.class.php(71): api\\billing::update(Object(model\\finance\\Bill))\n#2 [internal function]: rpc\\billing->update(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#5 {main}"}
2012-12-09T20:11:12+01:00 ERROR {"message":"No id set on the object","stack":"#0 \/var\/www\/apps\/billing\/api.class.php(226): helper\\lodo->update(Object(model\\finance\\Bill))\n#1 \/var\/www\/apps\/billing\/rpc.class.php(71): api\\billing::update(Object(model\\finance\\Bill))\n#2 [internal function]: rpc\\billing->update(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#5 {main}"}
2012-12-09T20:11:56+01:00 ERROR {"message":"No id set on the object","stack":"#0 \/var\/www\/apps\/billing\/api.class.php(226): helper\\lodo->update(Object(model\\finance\\Bill))\n#1 \/var\/www\/apps\/billing\/rpc.class.php(71): api\\billing::update(Object(model\\finance\\Bill))\n#2 [internal function]: rpc\\billing->update(Array)\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#5 {main}"}
2012-12-10T21:27:15+01:00 ERROR {"message":"Value of transaction has to be > 0","stack":"#0 \/var\/www\/helpers\/accounting\/controller.class.php(141): helper\\accounting->addTransaction(Object(model\\finance\\accounting\\Transaction))\n#1 \/var\/www\/apps\/accounting\/api.class.php(389): helper\\accounting->addDaybookTransaction(Object(model\\finance\\accounting\\DaybookTransaction))\n#2 \/var\/www\/apps\/billing\/api.class.php(307): api\\accounting::importTransactions(Object(model\\finance\\accounting\\DaybookTransaction), Array)\n#3 \/var\/www\/apps\/billing\/rpc.class.php(89): api\\billing::bookkeep('50c645a21a5f01f...', 12320, 13110)\n#4 [internal function]: rpc\\billing->post('50c645a21a5f01f...', 12320, 13110)\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-10T21:29:44+01:00 ERROR {"message":"Value of transaction has to be > 0","stack":"#0 \/var\/www\/helpers\/accounting\/controller.class.php(141): helper\\accounting->addTransaction(Object(model\\finance\\accounting\\Transaction))\n#1 \/var\/www\/apps\/accounting\/api.class.php(389): helper\\accounting->addDaybookTransaction(Object(model\\finance\\accounting\\DaybookTransaction))\n#2 \/var\/www\/apps\/billing\/api.class.php(307): api\\accounting::importTransactions(Object(model\\finance\\accounting\\DaybookTransaction), Array)\n#3 \/var\/www\/apps\/billing\/rpc.class.php(89): api\\billing::bookkeep('50c646371a5f01e...', 12320, 13110)\n#4 [internal function]: rpc\\billing->post('50c646371a5f01e...', 12320, 13110)\n#5 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#6 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#7 {main}"}
2012-12-10T22:00:47+01:00 ERROR {"message":"Currency has to be set.","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(270): model\\ext\\ubl2\\Invoice->doValidate(2)\n#1 \/var\/www\/model\/AbstractModel.class.php(275): model\\AbstractModel->validate(2)\n#2 \/var\/www\/apps\/invoice\/api.class.php(333): model\\AbstractModel->validate(2)\n#3 \/var\/www\/apps\/invoice\/api.class.php(170): api\\invoice::invoiceObject(Object(model\\finance\\Invoice))\n#4 \/var\/www\/apps\/invoice\/rpc.class.php(33): api\\invoice::create(Object(model\\finance\\Invoice))\n#5 [internal function]: rpc\\invoice->create(Array)\n#6 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#7 \/var\/www\/webroot\/index.php(179): core\\reqHandler::init()\n#8 {main}"}
2012-12-11T23:01:45+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '172.16.112.128' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(577): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(205): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(143): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(141): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/start\/finance\/controller.class.php(36): start\\finance\\api::login('madspbuch@gmail...', '123456')\n#6 [internal function]: start\\finance\\main->index()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#9 {main}"}
2012-12-12T13:10:03+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '172.16.112.128' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(577): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(205): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(143): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(141): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/start\/finance\/controller.class.php(36): start\\finance\\api::login('madspbuch@gmail...', '123456')\n#6 [internal function]: start\\finance\\main->index()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#9 {main}"}
2012-12-12T17:00:15+01:00 ERROR {"message":"Property \"line\" doesn't exist in model\\finance\\Bill","stack":"#0 \/var\/www\/model\/AbstractModel.class.php(117): model\\AbstractModel->set('line', Array)\n#1 \/var\/www\/helpers\/parser\/Post.class.php(88): model\\AbstractModel->__construct(Array)\n#2 \/var\/www\/apps\/billing\/controller.class.php(136): helper\\parser\\Post->getObj()\n#3 [internal function]: app\\billing->create()\n#4 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#5 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#6 {main}"}
2012-12-12T18:21:19+01:00 ERROR {"message":"Product \"\" not found","stack":"#0 \/var\/www\/apps\/products\/controller.class.php(74): api\\products::getOne('')\n#1 [internal function]: app\\products->view('')\n#2 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#3 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#4 {main}"}
2012-12-12T18:44:50+01:00 ERROR {"message":"Contact  doesn' exist","stack":"#0 \/var\/www\/apps\/billing\/api.class.php(159): api\\billing::billObject(Object(model\\finance\\Bill))\n#1 \/var\/www\/apps\/billing\/controller.class.php(141): api\\billing::create(Object(model\\finance\\Bill))\n#2 [internal function]: app\\billing->create()\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#5 {main}"}
2012-12-12T18:47:32+01:00 ERROR {"message":"Product \"\" not found","stack":"#0 \/var\/www\/apps\/products\/controller.class.php(74): api\\products::getOne('')\n#1 [internal function]: app\\products->view('')\n#2 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#3 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#4 {main}"}
2012-12-12T19:13:04+01:00 ERROR {"message":"Product \"stuff\" not found","stack":"#0 \/var\/www\/apps\/products\/controller.class.php(239): api\\products::getOne('stuff')\n#1 [internal function]: app\\products->getProduct('stuff')\n#2 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#3 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#4 {main}"}
2012-12-12T19:13:04+01:00 ERROR {"message":"Account stuff doesn't exist.","stack":"#0 \/var\/www\/apps\/accounting\/api.class.php(457): helper\\accounting->getAccount('stuff')\n#1 \/var\/www\/apps\/accounting\/controller.class.php(341): api\\accounting::getAccount('stuff')\n#2 [internal function]: app\\accounting->getAccount('stuff')\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#5 {main}"}
2012-12-12T19:13:52+01:00 ERROR {"message":"Account stuff doesn't exist.","stack":"#0 \/var\/www\/apps\/accounting\/api.class.php(457): helper\\accounting->getAccount('stuff')\n#1 \/var\/www\/apps\/accounting\/controller.class.php(341): api\\accounting::getAccount('stuff')\n#2 [internal function]: app\\accounting->getAccount('stuff')\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#5 {main}"}
2012-12-12T19:13:52+01:00 ERROR {"message":"Product \"stuff\" not found","stack":"#0 \/var\/www\/apps\/products\/controller.class.php(239): api\\products::getOne('stuff')\n#1 [internal function]: app\\products->getProduct('stuff')\n#2 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#3 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#4 {main}"}
2012-12-12T19:16:25+01:00 ERROR {"message":"Product \"stuff\" not found","stack":"#0 \/var\/www\/apps\/products\/controller.class.php(239): api\\products::getOne('stuff')\n#1 [internal function]: app\\products->getProduct('stuff')\n#2 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#3 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#4 {main}"}
2012-12-12T19:16:25+01:00 ERROR {"message":"Account stuff doesn't exist.","stack":"#0 \/var\/www\/apps\/accounting\/api.class.php(457): helper\\accounting->getAccount('stuff')\n#1 \/var\/www\/apps\/accounting\/controller.class.php(341): api\\accounting::getAccount('stuff')\n#2 [internal function]: app\\accounting->getAccount('stuff')\n#3 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#4 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#5 {main}"}
2012-12-14T13:13:00+01:00 ERROR {"message":"SQLSTATE[HY000] [2003] Can't connect to MySQL server on '172.16.112.128' (111)","stack":"#0 \/var\/www\/core\/db.class.php(49): PDO->__construct('mysql:dbname=co...', 'appf', 'appfDB')\n#1 \/var\/www\/core\/auth.class.php(577): core\\db->__construct(Array)\n#2 \/var\/www\/core\/auth.class.php(205): core\\auth->getDB()\n#3 \/var\/www\/core\/auth.class.php(143): core\\auth->validateUser('111', 'e4f85a81a01c023...')\n#4 \/var\/www\/start\/finance\/api.class.php(141): core\\auth->login('111', 'e4f85a81a01c023...')\n#5 \/var\/www\/start\/finance\/controller.class.php(36): start\\finance\\api::login('madspbuch@gmail...', '123456')\n#6 [internal function]: start\\finance\\main->index()\n#7 \/var\/www\/core\/reqHandler.class.php(131): call_user_func_array(Array, Array)\n#8 \/var\/www\/webroot\/index.php(180): core\\reqHandler::init()\n#9 {main}"}
